# Generated by Django 5.1.6 on 2025-02-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_db', '0003_departments_name_embedding_employees_email_embedding_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departments',
            table='departments',
        ),
        migrations.AlterModelTable(
            name='employees',
            table='employees',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
