# Generated by Django 5.1.6 on 2025-02-26 17:31

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_db', '0004_alter_departments_table_alter_employees_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='name_embedding',
            field=pgvector.django.vector.VectorField(blank=True, null=True, verbose_name=models.FloatField()),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email_embedding',
            field=pgvector.django.vector.VectorField(blank=True, null=True, verbose_name=models.FloatField()),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name_embedding',
            field=pgvector.django.vector.VectorField(blank=True, null=True, verbose_name=models.FloatField()),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer_name_embedding',
            field=pgvector.django.vector.VectorField(blank=True, null=True, verbose_name=models.FloatField()),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_embedding',
            field=pgvector.django.vector.VectorField(blank=True, null=True, verbose_name=models.FloatField()),
        ),
    ]
